apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app  # This should match the labels in your app deployment
  ports:
    - protocol: TCP
      port: 80  # Port to expose on the service
      targetPort: 3000  # Port that the app pods are listening on
  type: LoadBalancer  # Change to NodePort or ClusterIP if needed