apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # This should match the labels in your Nginx deployment
  ports:
    - protocol: TCP
      port: 80  # Port to expose on the service
      targetPort: 80  # Port that the Nginx pods are listening on
  type: NodePort  # Change to LoadBalancer or ClusterIP if needed